In [1]:
import tensorflow as tf
from tensorflow import keras
import os

2023-10-15 22:38:58.352638: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-15 22:38:58.352671: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-15 22:38:58.352703: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-15 22:38:58.359214: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
inp = tf.compat.v1.random_uniform([10, 10])

2023-10-15 22:39:23.812188: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-15 22:39:23.816771: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-15 22:39:23.816996: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

In [5]:
dataset = tf.data.Dataset.from_tensor_slices(inp)
dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(10,), dtype=tf.float32, name=None)>

In [6]:
dataset2 = dataset.map(lambda x: x*2)

In [14]:
elem = iter(dataset)
print(next(elem))
elem = iter(dataset2)
print(next(elem))

tf.Tensor(
[0.42997766 0.521546   0.11739182 0.8192972  0.6733048  0.25769866
 0.75546503 0.95243466 0.5708543  0.55160093], shape=(10,), dtype=float32)
tf.Tensor(
[0.8599553  1.043092   0.23478365 1.6385944  1.3466096  0.5153973
 1.5109301  1.9048693  1.1417086  1.1032019 ], shape=(10,), dtype=float32)


In [18]:
for elem in iter(dataset):
    print(elem)

tf.Tensor(
[0.42997766 0.521546   0.11739182 0.8192972  0.6733048  0.25769866
 0.75546503 0.95243466 0.5708543  0.55160093], shape=(10,), dtype=float32)
tf.Tensor(
[0.04748893 0.35692453 0.44591033 0.95246017 0.59599984 0.36678326
 0.8886422  0.5359055  0.23562777 0.08628309], shape=(10,), dtype=float32)
tf.Tensor(
[0.2496171  0.2097112  0.41755533 0.72290075 0.38581562 0.536428
 0.28383648 0.59830546 0.26242507 0.4064231 ], shape=(10,), dtype=float32)
tf.Tensor(
[0.66420674 0.03706729 0.40847695 0.9584966  0.04140508 0.67844796
 0.2926284  0.12962604 0.6726656  0.9211428 ], shape=(10,), dtype=float32)
tf.Tensor(
[0.72699714 0.53565896 0.95600903 0.32033825 0.8178257  0.74576056
 0.45146334 0.836607   0.43218994 0.3183937 ], shape=(10,), dtype=float32)
tf.Tensor(
[0.93705    0.2890662  0.41709352 0.60518813 0.73896694 0.45889246
 0.5274403  0.638026   0.19753313 0.29199862], shape=(10,), dtype=float32)
tf.Tensor(
[0.66668224 0.00241232 0.14148545 0.23807001 0.3509729  0.87734187
 0.441

In [21]:
batched_dataset = dataset.batch(2)
for elem in batched_dataset:
    print(elem)

tf.Tensor(
[[0.42997766 0.521546   0.11739182 0.8192972  0.6733048  0.25769866
  0.75546503 0.95243466 0.5708543  0.55160093]
 [0.04748893 0.35692453 0.44591033 0.95246017 0.59599984 0.36678326
  0.8886422  0.5359055  0.23562777 0.08628309]], shape=(2, 10), dtype=float32)
tf.Tensor(
[[0.2496171  0.2097112  0.41755533 0.72290075 0.38581562 0.536428
  0.28383648 0.59830546 0.26242507 0.4064231 ]
 [0.66420674 0.03706729 0.40847695 0.9584966  0.04140508 0.67844796
  0.2926284  0.12962604 0.6726656  0.9211428 ]], shape=(2, 10), dtype=float32)
tf.Tensor(
[[0.72699714 0.53565896 0.95600903 0.32033825 0.8178257  0.74576056
  0.45146334 0.836607   0.43218994 0.3183937 ]
 [0.93705    0.2890662  0.41709352 0.60518813 0.73896694 0.45889246
  0.5274403  0.638026   0.19753313 0.29199862]], shape=(2, 10), dtype=float32)
tf.Tensor(
[[0.66668224 0.00241232 0.14148545 0.23807001 0.3509729  0.87734187
  0.44126725 0.48597252 0.63671756 0.04163694]
 [0.0513593  0.3605702  0.53414726 0.88537717 0.74977744 

## MNIST

In [22]:
num_classes = 10
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
image_vector_size = 28*28
x_train = x_train.reshape(x_train.shape[0], image_vector_size)
x_test = x_test.reshape(x_test.shape[0], image_vector_size)
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

In [24]:
mnist_ds_train = tf.data.Dataset.from_tensor_slices((x_train, y_train))
mnist_ds_train

<_TensorSliceDataset element_spec=(TensorSpec(shape=(784,), dtype=tf.uint8, name=None), TensorSpec(shape=(10,), dtype=tf.float32, name=None))>

In [ ]:
x = keras.layers.Dense(128, activation = 'relu')(img)
x = keras.layers.Dense(128, activation = "relu")(x)
x = keras.layers.Dense(10, activation = "softmax")(x)